book/urls.py
from django.urls import path
from book.views import get_books


app_name = "book"

urlpatterns = [
    path('', get_books, name='get_books'),
]

librarium/urls.py
from django.contrib import admin
from django.urls import path, include
from loans.views import show_loans


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('api/books/', include('book.urls')),
    path('userprofile/', include(('userprofile.urls', 'userprofile'), namespace='userprofile')),
    path('collection/', include('collection.urls')),
    path('reviews/', include('reviews.urls')),
    path('book-request/', include('bookrequest.urls')),
    path('show_loans/', include('loans.urls')),
    path('auth/', include('authentication.urls')),
]

userprofile/urls.py
from django.urls import path, include
from userprofile.views import show_userprofile
from home.views import home, user_home
from userprofile.views import edit_profile
from userprofile.views import change_password
from userprofile.views import edit_profile_ajax
from userprofile.views import change_password_ajax, show_userprofile_api, change_password_flutter, edit_profile_flutter

app_name = 'userprofile'

urlpatterns = [
    path('', show_userprofile, name='show_userprofile'),
    path('user-page/', user_home, name='user_home'),
    path('edit_profile',edit_profile, name = 'edit_profile'),
    path('edit_profile_ajax',edit_profile_ajax, name = 'edit_profile_ajax'),
    path('change-password', change_password, name='change-password'),
    path('change_password_ajax', change_password_ajax, name='change_password_ajax'),
    path('api/show_userprofile/', show_userprofile_api, name='show_userprofile_api'),
    path('api/change_password/', change_password_flutter, name='change_password_flutter'),
    path('api/edit_profile/', edit_profile_flutter, name='edit_profile_flutter'),
]

userprofile/models.py
from django.db import models
from django.contrib.auth.models import User 
from home.forms import RegisterForm

# Create your models here.


class UserProfile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)

userprofile/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User 
from django.contrib.auth.forms import UserCreationForm


class EditProfileForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))

    class Meta:
        model = User
        fields = ['username', 'email']

userprofile/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User 
from home.forms import RegisterForm
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from userprofile.forms import EditProfileForm
from django.urls import reverse_lazy
from django.contrib.auth.views import PasswordChangeView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import update_session_auth_hash
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse, HttpResponseBadRequest
from loans.models import LoansBook
from reviews.models import Review
from bookrequest.models import BookReq
import json

# Create your views here.




@login_required
def show_userprofile(request):
    CountLoansBook = LoansBook.objects.filter(user = request.user).count()
    CountReviewBook = Review.objects.filter(user = request.user).count()
    CountRequestBook = BookReq.objects.filter(user = request.user).count()
    context = {
        'CountLoansBook': CountLoansBook,
        'CountReviewBook': CountReviewBook,
        'CountRequestBook': CountRequestBook
    }

    return render(request, "userprofile.html", context)

def show_userprofile_api(request):


    CountLoansBook = LoansBook.objects.filter(user=request.user).count()
    CountReviewBook = Review.objects.filter(user=request.user).count()
    CountRequestBook = BookReq.objects.filter(user=request.user).count()

    data = {
        'CountLoansBook': CountLoansBook,
        'CountReviewBook': CountReviewBook,
        'CountRequestBook': CountRequestBook
    }

    return JsonResponse(data)

@login_required
@csrf_exempt
def edit_profile_ajax(request):
    if request.method == 'POST':
        user_form = EditProfileForm(request.POST, instance=request.user)

        if user_form.is_valid():
            user_form.save()
            response_data = {'message': 'Profil kamu berhasil diubah!'}
        else:
            response_data = {'message': 'Gagal mengubah profil. Cek isian form kamu.'}

        #return HttpResponse(response_data)

        return JsonResponse(response_data)
    else:
        user_form = EditProfileForm(instance=request.user)

    return render(request, 'userprofile.html', {'user_form': user_form})



@login_required
def edit_profile(request):
    if request.method == 'POST':
        user_form = EditProfileForm(request.POST, instance=request.user)

        if user_form.is_valid():
            user_form.save()
            return redirect(to='userprofile.html')
    else:
        user_form = EditProfileForm(instance=request.user)

    return render(request, 'userprofile.html', {'user_form': user_form})


@csrf_exempt
def edit_profile_flutter(request):
    if request.method == 'POST':
        try:
            data = json.loads(request.body)
            user_form = EditProfileForm(data, instance=request.user)
            if user_form.is_valid():
                user_form.save()
                return JsonResponse({'message': 'Email successfully changed'}, status=201)
            else:
                return JsonResponse({'error': user_form.errors}, status=400)
        except json.JSONDecodeError:
            return JsonResponse({'error': 'Invalid JSON format'}, status=400)
    else:
        return JsonResponse({'error': 'Invalid request method'}, status=400)





@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Ini biar session masih tetap aktif
            return redirect('userprofile.html')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'change_password.html', {'form': form})



@login_required
def change_password_ajax(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Ini biar session masih tetap aktif
            return HttpResponse(b"CREATED", status=201)
    else:
        form = PasswordChangeForm(request.user)   
     
    return JsonResponse({'message': 'Invalid request.'}, status=400)

@csrf_exempt
def change_password_flutter(request):
    if request.method == 'POST':
        try:
            data = json.loads(request.body)
            form = PasswordChangeForm(request.user, data)
            if form.is_valid():
                user = form.save()
                update_session_auth_hash(request, user)
                return JsonResponse({'message': 'Password successfully changed'}, status=201)
            else:
                return JsonResponse({'error': form.errors}, status=400)
        except json.JSONDecodeError:
            return JsonResponse({'error': 'Invalid JSON format'}, status=400)
    else:
        return JsonResponse({'error': 'Invalid request method'}, status=400)

userprofile/templates/change_password.html
{% extends 'base.html' %}
{% block content %}
<li>
    <a class="dropdown-item d-flex align-items-center" href="{% url 'userprofile:change-password' %}">
      <i class="bi bi-person"></i>
      <span>Account Settings</span>
    </a>
  </li>
  <li>
    <hr class="dropdown-divider">
  </li>
    <h2>Change Password</h2>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Change Password</button>
    </form>
{% endblock content %}

userprofile/templates/navbar2.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home' %}">librarium</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Dropdown
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="#">Action</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" aria-disabled="true">Disabled</a>
          </li>
        </ul>
        <form class="d-flex" role="search">
          <!-- <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"> -->
          {% if user.is_authenticated %}
          <div class="dropdown" style="display: flex; align-items: center;">
            <span class="d-md-block dropdown-toggle ps-2 me-3" href="#" id="usernametextprofiledetailsdropdown1" data-bs-toggle="dropdown" role="button" aria-expanded="false" style="color: white;">{{user.username}}</span>
            <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile" aria-hidden="true" data-popper-placement="bottom-end" style="position: absolute; inset: 0px 0px auto auto; margin: 0px; transform: translate3d(-16px, 38px, 0px);">
              <li class="dropdown-header">
                <h6 id="usernametextprofiledetailsdropdown2">{{user.username}}</h6>
              </li>
              <li>
                <hr class="dropdown-divider">
              </li>
  
              <li>
                <a class="dropdown-item d-flex align-items-center" href="{% url 'home' %}">
                  <i class="bi bi-person"></i>
                  <span>Home</span>
                </a>
              </li>
              <li>
                <hr class="dropdown-divider">
              </li>

  
              <li>
                <a class="dropdown-item d-flex align-items-center" data-bs-toggle="modal" data-bs-target="#exampleModal2" href='#'>
                  <i class="bi bi-question-circle"></i>
                  <span>Need Help?</span>
                </a>
              </li>
              <li>
                <hr class="dropdown-divider">
              </li>
  
              <li>
                <a class="dropdown-item d-flex align-items-center" href="{% url 'logout' %}">
                  <i class="bi bi-box-arrow-right"></i>
                  <span>Sign Out</span>
                </a>
              </li>
  
            </ul>
            <a class="btn btn-outline-danger" type="submit" href="{% url 'logout' %}">Logout</a>
          </div> 
          {% else %}
          <button class="btn btn-outline-success me-3" type="button" data-bs-toggle="modal" data-bs-target="#exampleModal">Login</button>
          <a class="btn btn-outline-info" type="submit" href="{% url 'register' %}">Register</a>
          {% endif %}
        </form>
      </div>
    </div>
</nav>

{% load static %}
<script type="application/javascript" src="{% static 'js/userprofile.js' %}">


  
</script>

userprofile/templates/userprofile.html
{% extends 'base.html' %}
{% load static %}



{% block content %}
{% include 'navbar.html' %}
<style>
    .card {
        background-color: rgba(224, 236, 244);
    }

</style>

<div class="modal fade" id="exampleModal2" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Contact Support</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>- Nurin Farzana Nafiah (2206082695)</p>
                <p>- Calista Sekar Pamaja (2206082064)</p>
                <p>- Muhammad Nanda Pratama (2206081654)</p>
                <p>- Fazle Ilahi Bimo Aji (2206081446)</p>
                <p>- Resanda Dezca Asyam (2206082682)</p>
            
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Tutup</button>
            </div>
        </div>
    </div>
</div>

<div id="alert_placeholder"></div>

<div id="success-message" style="color: green;"></div>
<div id="error-message" style="color: red;"></div>

<main id="main" class="main">

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 text-center">
                <h1 class="display-4">Profile</h1>
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb justify-content-center bg-transparent py-2">
                        <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Account Settings</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
    

    <section class="section profile">
      <div class="row d-flex justify-content-center">

        <div class="col-xl-8">

          <div class="card">
            <div class="card-body pt-3">
              <!-- Bordered Tabs -->
              <ul class="nav nav-tabs nav-tabs-bordered" role="tablist">

                <li class="nav-item" role="presentation">
                  <button id="button1" class="nav-link active" data-bs-toggle="tab" data-bs-target="#profile-overview" aria-selected="true" role="tab">Overview</button>
                </li>

                <li class="nav-item" role="presentation">
                  <button id="button2" class="nav-link" data-bs-toggle="tab" data-bs-target="#profile-edit" aria-selected="true" tabindex="-1" role="tab">Edit Profile</button>
                </li>


                <li class="nav-item" role="presentation">
                  <button id="button4" class="nav-link" data-bs-toggle="tab" data-bs-target="#profile-change-password" aria-selected="false" tabindex="-1" role="tab">Change Password</button>
                </li>

              </ul>
              <div class="tab-content pt-2">

                <div class="tab-pane fade show active profile-overview" id="profile-overview" role="tabpanel">

                  <h5 class="card-title">Profile Details</h5>

                  <div class="row">
                    <div class="col-lg-3 col-md-4 label ">User Name</div>
                    <div id="usernametextprofiledetails" class="col-lg-9 col-md-8">{{user.username}}</div>
                  </div>

                  <div class="row">
                    <div class="col-lg-3 col-md-4 label">Email</div>
                    <div id="useremailtextprofiledetails" class="col-lg-9 col-md-8">{{user.email}}</div>
                  </div>


                  <div class="row">
                    <div class="col-lg-3 col-md-4 label">Number of Loan Books</div>
                    <div id="useremailtextprofiledetails" class="col-lg-9 col-md-8">{{ CountLoansBook }}</div>
                  </div>

                  <div class="row">
                    <div class="col-lg-3 col-md-4 label">Number of Review Books</div>
                    <div id="useremailtextprofiledetails" class="col-lg-9 col-md-8">{{CountReviewBook }}</div>
                  </div>

                  <div class="row">
                    <div class="col-lg-3 col-md-4 label">Number of Request Books</div>
                    <div id="useremailtextprofiledetails" class="col-lg-9 col-md-8">{{CountRequestBook }}</div>
                  </div>

                </div>

                <div class="tab-pane fade profile-edit pt-3" id="profile-edit" role="tabpanel">

                  <!-- Profile Edit Form -->
                  <form id="edit-profile-form">
                    {% csrf_token %}
                    <div class="row mb-3">
                      <label for="username" class="col-md-3 col-form-label">User Name</label>
                      <div class="col-md-9">
                        <input id="inputusername" type="text" class="form-control" id="username" name="username" value="{{user_form.username}}">
                      </div>
                    </div>
                    <div class="row mb-3">
                      <label for="email" class="col-md-3 col-form-label">Email</label>
                      <div class="col-md-9">
                        <input id="inputuseremail" type="text" class="form-control" id="email" name="email" value="{{user_form.email}}">
                      </div>
                    </div>
                    <div class="text-center">
                      <button type="button" class="btn btn-primary" onclick="saveChanges()">Save Changes</button>
                    </div>
                  </form>

                  </div>



                <div class="tab-pane fade pt-3" id="profile-change-password" role="tabpanel">
                    <h1>Rules:</h1>
                    <a>- Your password can't be too similar to your other personal information.</a><br>
                    <a>- Your password must contain at least 8 characters.</a><br>
                    <a>- Your password can't be a commonly used password.</a><br>
                    <a>- Your password can't be entirely numeric.</a><br>
                    <a>- Your current password must be valid.</a><br>
                    <a>- Your new password and re-enter new password must be valid and the same.</a><br>
                    
                  <!-- Change Password Form -->
                  <form id="change-password-form">
                    {% csrf_token %}
                    <div class="row mb-3">
                      <label for="id_old_password" class="col-md-4 col-lg-3 col-form-label">Current Password</label>
                      <div class="col-md-8 col-lg-9">
                        <input name="old_password" type="password" class="form-control" id="id_old_password">
                      </div>
                    </div>

                    <div class="row mb-3">
                      <label for="id_new_password1" class="col-md-4 col-lg-3 col-form-label">New Password</label>
                      <div class="col-md-8 col-lg-9">
                        <input name="new_password1" type="password" class="form-control" id="id_new_password1">
                      </div>
                    </div>

                    <div class="row mb-3">
                      <label for="id_new_password2" class="col-md-4 col-lg-3 col-form-label">Re-enter New Password</label>
                      <div class="col-md-8 col-lg-9">
                        <input name="new_password2" type="password" class="form-control" id="id_new_password2">
                      </div>
                    </div>

                    <div class="text-center">
                      <button type="button" class="btn btn-primary" onclick="savePassword()">Change Password</button>
                    </div>
                  </form><!-- End Change Password Form -->

                </div>

              </div><!-- End Bordered Tabs -->

            </div>
          </div>

        </div>
      </div>
    </section>

  </main>



{% load static %}
<script type="application/javascript" src="{% static 'js/userprofile2.js' %}">



    
</script>

{% endblock content %}