book/urls.py
from django.urls import path
from book.views import get_books


app_name = "book"

urlpatterns = [
    path('', get_books, name='get_books'),
]

librarium/urls.py
from django.contrib import admin
from django.urls import path, include
from loans.views import show_loans


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('api/books/', include('book.urls')),
    path('userprofile/', include(('userprofile.urls', 'userprofile'), namespace='userprofile')),
    path('collection/', include('collection.urls')),
    path('reviews/', include('reviews.urls')),
    path('book-request/', include('bookrequest.urls')),
    path('show_loans/', include('loans.urls')),
    path('auth/', include('authentication.urls')),
]

reviews/urls.py
from django.urls import path
from reviews.views import show_main, get_book_json, add_review_ajax, review_sheet, review_page, back_to_main, get_review_by_user_json, get_book_by_id_json
from reviews.views import get_review_json, book_details, edit_review, get_review_by_id_json, delete_review, get_book_user, get_book_by_id_json_mob, create_review_flutter
from reviews.views import get_rev_by_user_json_mob, get_rev_by_book_json_mob, get_user_by_id_mob

app_name = 'reviews'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('get-book-json/', get_book_json, name='get_book_json'),
    path('get-book-user/', get_book_user, name='get_book_user'),
    path('get-review-json/', get_review_json, name='get_review_json'),
    path('get-book-by-id/<int:id>/', get_book_by_id_json, name='get_book_by_id_json'),
    path('get-review-by-id/<int:id>/', get_review_by_id_json, name='get_review_by_id_json'),
    path('get-review-by-user/', get_review_by_user_json, name='get_review_by_user_json'),
    path('add-review/', add_review_ajax, name='add_review_ajax'),
    path('review-page/', review_page, name='review_page'),
    path('review-sheet/<int:id>', review_sheet, name='review_sheet'),
    path('back_main/', back_to_main, name='back_to_main'),
    path('book-details/<int:book_id>/', book_details, name='book_details'),
    path('edit-review/<int:review_id>/', edit_review, name='edit_review'),
    path('delete-review/<int:id>/', delete_review, name='delete_review'),
    path('get-book-by-id-mob/<int:id>/', get_book_by_id_json_mob, name='get_book_by_id_json_mob'),
    path('get-rev-by-user-mob/', get_rev_by_user_json_mob, name='get_rev_by_user_json_mob'),
    path('get-rev-by-book-mob/<int:id>/', get_rev_by_book_json_mob, name='get_rev_by_book_json_mob'),
    path('get-user-by-id-mob/<int:id>/', get_user_by_id_mob, name='get_user_by_id_mob'),
    path('create-review/', create_review_flutter, name='create_review_flutter'),

]

reviews/models.py
from django.db import models
from django.contrib.auth.models import User
from book.models import Book

# Create your models here.
class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    date_added = models.DateField(auto_now_add=True)
    rating = models.FloatField()
    book_review_desc = models.TextField()
    is_recommended = models.BooleanField()

reviews/forms.py
from django.forms import ModelForm
from reviews.models import Review
from django.contrib.auth.models import User 
from django.contrib.auth.forms import UserCreationForm
from django import forms


class ReviewForm(ModelForm): 
    rating = forms.FloatField(widget=forms.TextInput(attrs={'class':'form-control'}))
    book_review_desc = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    is_recommended = forms.BooleanField(widget=forms.CheckboxInput(attrs={'class':'form-check-input'}))

    class Meta:
        model = Review
        fields = ["rating", "book_review_desc", "is_recommended"]
    
    def custom_error_display(self):
        error_string = ""
        for field, errors in self.errors.items():
            error_string += errors
        return error_string

reviews/views.py
import json
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseNotFound, JsonResponse
from django.core import serializers
from book.models import Book
from reviews.models import Review
from reviews.forms import ReviewForm
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User



@login_required(login_url='../login')
def show_main(request):
    books = Book.objects.all()
    reviews = Review.objects.all()
    this_user_reviews = Review.objects.filter(user=request.user)
    total_reviews = Review.objects.filter(user=request.user).count()

    context = {
        'user' : request.user,
        'books' : books,
        'reviews' : reviews,
        'this_user_reviews' : this_user_reviews,
        'total_reviews' : total_reviews,
    }
    return render(request, "main.html", context)

def review_page(request):
    books = Book.objects.all()
    reviews = Review.objects.all()
    form = ReviewForm()
    context = {
        'user' : request.user,
        'books' : books,
        'reviews' : reviews,
        'form' : form,
    }
    return render(request, "review_page.html", context)

def book_details(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    reviews = Review.objects.filter(book_id = book_id)
    context = {
        'user' : request.user,
        'book' : book,
        'reviews' : reviews,
    }
    return render(request, "book_details.html", context)


def get_book_by_id_json(request, id):
    book = Book.objects.get(pk=id)
    book_data = {
        'title': book.title,
        'author': book.author,
        'year': book.year,
        'publisher': book.publisher,
        'image_m': book.image_m,
        'image_l': book.image_l,
    }
    return JsonResponse(book_data)

def get_review_by_id_json(request, id):
    review = get_object_or_404(Review, pk=id)
    review_data = {
        'book': review.book,
        'user': request.user,
        'book_review_desc': review.book_review_desc,
        'rating': review.rating,
        'is_recommended': review.is_recommended,
    }
    return JsonResponse(review_data)

def update_review(request, review_id):
    try:
        review = Review.objects.get(pk=review_id)
        review.rating = request.POST['rating']
        review.book_review_desc = request.POST['book_review_desc']
        review.is_recommended = request.POST['is_recommended']
        review.save()
        return JsonResponse({'message': 'Review updated successfully'})
    except Review.DoesNotExist:
        return JsonResponse({'error': 'Review not found'}, status=404)
    except Exception as e:
        return JsonResponse({'error': str(e)}, status=500)


def get_review_by_user_json(request):
    user = request.user
    reviews = Review.objects.filter(user=user)
    review_data = []

    for review in reviews:
        review_data.append({
            'id' : review.id,
            'book_id': review.book.id,
            'book_title': review.book.title,  # Include the book title
            'rating': review.rating,
            'book_review_desc': review.book_review_desc,
            'is_recommended': review.is_recommended,
            'date_added': review.date_added,
        })

    return JsonResponse({'reviews': review_data})

def get_book_json(request):
    books = Book.objects.all()
    return HttpResponse(serializers.serialize('json', books))

def get_book_user(request):
    user_reviewed_books = Review.objects.filter(user=request.user).values_list('book', flat=True)
    books = Book.objects.exclude(pk__in=user_reviewed_books)

    return HttpResponse(serializers.serialize('json', books))

def get_review_json(request):
    reviews = Review.objects.all()
    return HttpResponse(serializers.serialize('json', reviews))

def back_to_main(request):
    return HttpResponseRedirect(reverse('reviews:show_main'))

@csrf_exempt
def add_review_ajax(request):
    
    if request.method == 'POST':
        rating = request.POST.get('rating')
        book_id = request.POST.get('book_id')
        book_review_desc = request.POST.get('book_review_desc')
        is_recommended = request.POST.get('is_recommended')
        if is_recommended == 'yes':
            is_recommended = True
        else:
            is_recommended = False

        book = Book.objects.get(pk = book_id)

        review = Review(
            user=request.user,
            book=book, 
            rating=rating,
            book_review_desc=book_review_desc,
            is_recommended=bool(is_recommended)
        )
        review.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

def review_sheet(request, id):
    form = ReviewForm()
    book = get_object_or_404(Book, pk=id)

    if request.method == "POST":
        form = ReviewForm(request.POST)
        if form.is_valid():
            form.save()
        return HttpResponseRedirect(reverse('reviews:show_main'))
            
    context = {
        'form':form,
        'book':book,
    }
    return render(request, 'review_sheet.html', context)

@csrf_exempt
def delete_review(request, id):
    try:
        review = Review.objects.get(pk=id)
        review.delete()
        return JsonResponse({'message': 'Review deleted successfully'})
    except Review.DoesNotExist:
        return JsonResponse({'message': 'Review item not found'}, status=404)
    
@csrf_exempt
def edit_review(request, review_id):
    review = get_object_or_404(Review, pk=review_id)
    form = ReviewForm(request.POST or None, instance=review)

    if request.method == 'POST':
        review.rating = request.POST.get("edit_rating")
        review.book_review_desc = request.POST.get("edit_desc")
        is_recommended = request.POST.get('edit_is_recommended')
        if is_recommended == 'yes':
            is_recommended = True
        else:
            is_recommended = False
        review.is_recommended = bool(is_recommended)
        review.user = request.user
        review.save()


        return HttpResponse(b"UPDATED", status=201)

    return HttpResponseNotFound()

# @csrf_exempt
# def edit_review(request, review_id):
#     review = get_object_or_404(Review, pk=review_id)
#     form = ReviewForm(request.POST or None, instance=review)


#     if form.is_valid() and request.method == "POST":
#         # Simpan form dan kembali ke halaman awal
#         form.save()
#         return HttpResponseRedirect(reverse('reviews:show_main'))

#     context = {'form': form}
#     print("hello")
#     return render(request, "review_sheets.html", context)



def add_review_form(request):
    form = ReviewForm(request.POST or None)
    book_id = request.POST.get('book_id')
    book = Book.objects.get(pk = book_id)
    print(book_id)

    if request.method == "POST":
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.user = request.user
            review.book = book
            review.save()
            messages.success(request, 'Your review has been successfully created!')
            return redirect('reviews:show_main')
            
    context = {'form':form}
    return render(request, 'create_review.html', context)

@csrf_exempt
def create_review_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)
        book_id = data["book_id"]
        book = Book.objects.get(pk = book_id)

        new_review = Review.objects.create(
            user = request.user,
            book = book,
            is_recommended = bool(data["is_recommended"]),
            rating = int(data["rating"]),
            book_review_desc = data["book_review_desc"]
        )
        new_review.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

# NEW FOR MOBDEV
def get_book_by_id_json_mob(request, id):
    book = Book.objects.get(pk=id)
    book_data = {
        'model': "book.book",
        'pk': id,
        'fields':{
            'ISBN': book.ISBN,
            'title': book.title,
            'author': book.author,
            'year': book.year,
            'publisher': book.publisher,
            'image_s': book.image_s,
            'image_m': book.image_m,
            'image_l': book.image_l
        }
    }
    print(book_data)
    return JsonResponse(book_data)

def get_rev_by_user_json_mob(request):
    user = request.user
    reviews = Review.objects.filter(user=user)
    review_data = []
    for review in reviews:
        review_data.append({
            'model': 'reviews.review',
            'pk' : review.pk,
            'fields':{
                'user': review.user.pk,
                'book': review.book.pk,
                'book_review_desc': review.book_review_desc,
                'rating': review.rating,
                'is_recommended': review.is_recommended,
                'date_added': review.date_added,
            }
        })
    return HttpResponse(serializers.serialize('json', reviews))

# def get_rev_by_user_json_mob(request):
#     user = request.user
#     reviews = Review.objects.filter(user=user)
#     review_data = []
#     for review in reviews:
#         review_data.append({
#             'model': 'reviews.review',
#             'pk' : review.pk,
#             'fields':{
#                 'user': review.user.pk,
#                 'book': review.book.pk,
#                 'book_review_desc': review.book_review_desc,
#                 'rating': review.rating,
#                 'is_recommended': review.is_recommended,
#                 'date_added': review.date_added,
#             }
#         })
    # return HttpResponse(serializers.serialize('json', reviews))

reviews/templates/book_details.html
{% extends 'base.html' %}


{% block content %}

{% include 'navbar.html' %}
    <div class="col-lg-7 offset-lg-2 mt-5">
        <h1 class="display-5">Book Details</h1>

        <div class="row">
            <div class="col-sm-4">
                <div class="image-container text-center">
                    <img src="{{book.image_l}}" alt="Book Cover" style="max-height: 400px;">
                </div>
            </div>
            <div class="col-sm-8">
                <h1 class="display-4">{{ book.title }}</h1>
                <table class="table table-hover">
                    <tr>
                        <td>Author</td>
                        <td>{{ book.author }}</td>
                    </tr>
                    <tr>
                        <td>Year</td>
                        <td>{{ book.year }}</td>
                    </tr>
                    <tr>
                        <td>ISBN</td>
                        <td>{{ book.ISBN }}</td>
                    </tr>
                </table>
            </div>
        </div>
        <div class="row">
            <h1 class="display-6">Others say..</h1>
            {% for review in reviews %}
            <div class="shadow mb-3 bg-body">
                <div class="row">
                    <div class="card">
                        <div class="card-body">
                            <p class="card-text">{{review.user.username}} gives {{review.rating}} out of 5</p>                            
                            <p class="card-text">{{review.book_review_desc}}</p>
                            {% if review.is_recommended %}
                            <p class="card-text">{{review.user.username}} recommend this!</p>
                            {% else %}
                            <p class="card-text">{{review.user.username}} doesn't recommend this</p>
                            {% endif %}
                            <div class="card-footer">
                                <small class="text-muted">Date Added {{review.date_added}}</small>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

{% endblock content %}

 

reviews/templates/review_page.html
{% extends 'base.html' %}

{% load static %}


{% block content %}
    {% include 'navbar.html' %}

        <div class="col-lg-7 offset-lg-2 mt-5">

            <h1 class="display-2">Choose one book to review</h1>

            <!-- KATALOG -->
            <div class='row' id="book_card"></div>
        </div>

    <div class="modal fade" id="reviewModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Review Sheet</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <h5 class="card-text font-weight-bold text-center" style="text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.3);" id="reviewModalTitle"></h5>
                    <div class="image-container-modal my-3 text-center">
                        <img id="reviewModalCover" alt="Book Cover" style="width: 106px; height: 160px;">
                    </div>
                    <table class="table table-hover">
                        <tr>
                            <td>Author</td>
                            <td id="reviewModalAuthor"></td>
                        </tr>
                        <tr>
                            <td>Year</td>
                            <td id="reviewModalYear"></td>
                        </tr>
                        <tr>
                            <td>ISBN</td>
                            <td id="reviewModalISBN"></td>
                        </tr>
                    </table>

                    <small class="text-muted" id="reviewModalBookId"></small>
                    <form id="form" onsubmit="return false;">
                        {% csrf_token %}
                        <div class="form-group mb-3">
                            <label for="rating" class="form-label">Book Rating on scale 0-5</label>
                            <input type="range" class="form-range" min="0" max="5" id="rating" name="rating" required>
                        </div>
                        <div class="form-group mb-3">
                            <p>What are your thoughts about this book?</p>
                            <textarea class="form-control" id="book_review_desc" name="book_review_desc" required></textarea>
                        </div>
                        <div class="form-group mb-3">
                            <p>Would you recommend this book?</p>
                            <div class="btn-group" data-toggle="buttons">
                                <label class="btn btn-primary">
                                    <input type="radio" name="is_recommended" value="yes" checked> Yes
                                </label>
                                <label class="btn btn-secondary">
                                    <input type="radio" name="is_recommended" value="no"> No
                                </label>
                            </div>                       
                         </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="add_review_btn" data-bs-dismiss="modal">Add Review</button>
                </div>
            </div>
        </div>
    </div>

        <!-- Notification Modal -->
    <div class="modal fade" id="notificationModal" tabindex="-1" aria-labelledby="notificationModalLabel" aria-hidden="true">
        <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="notificationModalLabel">Notification</h5>
            </div>
            <div class="modal-body" id="notificationMessage">
            </div>
            <a href="{% url 'reviews:back_to_main' %}" class="btn btn-primary">OK</a>

        </div>
        </div>
    </div>
    
  
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>


    <script>
         async function getBooks() {
            return fetch("{% url 'reviews:get_book_user' %}").then((res) => res.json())
        }

    async function openReviewModalWithBookData(bookTitle, bookAuthor, bookYear, bookISBN, bookCoverURL, bookId) {
        document.getElementById('reviewModalBookId').value = bookId;
        document.getElementById('reviewModalTitle').textContent = bookTitle;
        document.getElementById('reviewModalCover').src = bookCoverURL;
        document.getElementById('reviewModalAuthor').textContent = bookAuthor;
        document.getElementById('reviewModalYear').textContent = bookYear;
        document.getElementById('reviewModalISBN').textContent = bookISBN;
        $('#reviewModal').modal('show');
    }

    const placeholderImageUrl = "{% static 'BLANK.png' %}";

    async function refreshBookCards() {
        document.getElementById("book_card").innerHTML = "";
        const books = await getBooks();
        let htmlString = ` <div class="row row-cols-1 row-cols-md-4 mb-3 text-center">`;

        books.forEach((book) => {
            const bookImageUrl = getBookImageUrl(book);
            htmlString += `
                <div class="col mb-4">
                    <div class="shadow mb-3 bg-body">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title font-weight-bold" style="text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.3);">${book.fields.title}</h5>
                                <div class="image-container ">
                                    <img src="${bookImageUrl}" alt="Book Cover" style="width: 106px; height: 160px;">
                                </div>
                                <p></p>
                                <h6 class="card-text">${book.fields.author}</h6>
                                <p>${book.fields.year}</p>

                                <button
                                    type="button"
                                    class="btn btn-primary review-button"
                                    data-bs-toggle="modal"
                                    data-bs-target="#reviewModal"
                                    data-book-title="${book.fields.title}"
                                    data-book-cover="${bookImageUrl}"
                                    data-book-author="${book.fields.author}"
                                    data-book-year="${book.fields.year}"
                                    data-book-ISBN="${book.fields.ISBN}"
                                    data-book-id="${book.pk}"
                                >
                                    Review this Book
                                </button>
                                <p></p>

                                <div class="card-footer">
                                    <small class="text-muted">ISBN ${book.fields.ISBN}</small>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                `;
        });

        htmlString += `</div>`;
        document.getElementById("book_card").innerHTML = htmlString;

        const reviewButtons = document.querySelectorAll('.review-button');
        reviewButtons.forEach((button) => {
            button.addEventListener('click', function () {
                const bookTitle = this.getAttribute('data-book-title');
                const bookCoverURL = this.getAttribute('data-book-cover');
                const bookAuthor = this.getAttribute('data-book-author');
                const bookYear = this.getAttribute('data-book-year');
                const bookISBN = this.getAttribute('data-book-ISBN');
                const bookId = this.getAttribute('data-book-id');

                openReviewModalWithBookData(bookTitle, bookAuthor, bookYear, bookISBN, bookCoverURL, bookId);
            });
        });
    }
    refreshBookCards()

    function getBookImageUrl(book) {

        const imageUrl = book.fields.image_m;

        const img = new Image();

        img.src = imageUrl;

        img.onload = function () {
            if (img.width <= 5 || img.height <= 5) {
                img.src = placeholderImageUrl;
            }
         };

        return img.src;
    }

    async function addReview() {
        const bookId = document.getElementById('reviewModalBookId').value;
        const data = new FormData(document.querySelector('#form'));
        data.append('book_id', bookId); 

        fetch("{% url 'reviews:add_review_ajax' %}", {
                method: "POST",
                body: data
            }).then((response) => {
                if (response.status === 201) {
                    displayNotification('Your review has been successfully added!');
                    refreshBookCards();
                    document.getElementById("form").reset();
                } else {
                    displayNotification('Failed to add review :( Please try again.');
                }
                })
                .catch((error) => {
                    displayNotification('An error occurred. Please try again.');
                });
            return false
        }

        document.getElementById("add_review_btn").onclick = addReview


        function displayNotification(message) {
            const notificationMessage = document.getElementById('notificationMessage');
            notificationMessage.textContent = message;
            $('#notificationModal').modal('show');
        }
    
    </script>

{% endblock content %}

reviews/templates/review_sheets.html
{% extends 'base.html' %} 

{% block content %}

<div class="col-lg-7 offset-lg-2 mt-5">
    <h1>Review Sheets</h1>
    
    <form method="POST">
        {% csrf_token %}
            <div class="form-group mb-3">
                <label for="rating">Book Ratings</label>
                {{ form.rating }}
            </div>
            <div class="form-group mb-3">
                <p>What are your thoughts about this book?</p>
                {{ form.book_review_desc }}
            </div>
            <div class="form-group mb-3">
                <p>Would you recommend this book?</p>
                {{ form.is_recommended }}                       
            </div>
    <div>
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-primary" value="Edit Review">Edit Review</button>
    </div>
    
    </form>
</div>


{% endblock %}